# Generated by Django 5.0.6 on 2024-06-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mal_id', models.IntegerField(unique=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('images', models.JSONField(blank=True, null=True)),
                ('trailer', models.JSONField(blank=True, null=True)),
                ('titles', models.JSONField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('title_english', models.CharField(blank=True, max_length=255, null=True)),
                ('title_japanese', models.CharField(blank=True, max_length=255, null=True)),
                ('title_synonyms', models.JSONField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('episodes', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('airing', models.BooleanField(default=False)),
                ('aired', models.JSONField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('rating', models.CharField(blank=True, max_length=50, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('scored_by', models.IntegerField(blank=True, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('popularity', models.IntegerField(blank=True, null=True)),
                ('members', models.IntegerField(blank=True, null=True)),
                ('favorites', models.IntegerField(blank=True, null=True)),
                ('synopsis', models.TextField(blank=True, null=True)),
                ('background', models.TextField(blank=True, null=True)),
                ('season', models.CharField(blank=True, max_length=20, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('studios', models.JSONField(blank=True, null=True)),
                ('genres', models.JSONField(blank=True, null=True)),
                ('explicit_genres', models.JSONField(blank=True, null=True)),
                ('relations', models.JSONField(blank=True, null=True)),
                ('theme', models.JSONField(blank=True, null=True)),
                ('external', models.JSONField(blank=True, null=True)),
                ('streaming', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
